disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
line_length: 200

type_body_length:
  - 300 # warning
  - 400 # error

file_length:
  warning: 500
  error: 1200
identifier_name:
  min_length: 2

type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 50
    error: 60
  excluded: iPhone # excluded via string

function_parameter_count:
  warning: 6

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)

